### ISSUE TITLE
Episode: Icebreakers

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#110]
On Day 2, if there is time, add an episode on icebreakers, could be used already in beginning to "break the ice"
Or merged with collaborative notes.

**Comment by samumantha** [comment]
Check also #95  :)

**Comment by bast** [comment]
Sorry I should have coordinated this but didn't see this suggestion.

**Comment by samumantha** [comment]
Na, it's fine, there is so much in Session 2 already! 
I'll check for session 3 :)

**Comment by samumantha** [comment]
Also no time in session 3, lets leave it out for now, but still collect all the cool icebreaker ideas in #95
