### ISSUE TITLE
Episode: CodeRefinery intro

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#134]
- what is coderefinery
- history
- learner personas
- relation to carpentries
- ...?

**Comment by samumantha** [comment]
In current CodeRefinery intro we talk about best practices. Should this be "good enough"?

**Comment by bast** [comment]
Yes I also prefer "good enough".

**Comment by samumantha** [comment]
To Do: 
- [ ] Shorten to fit intro of day 2
- [ ] reduce/shorten impact and link to first session episode on feedback
- [ ] Shorten target audience section
- [ ] Add box about target audience level difficulties 
- [ ] replace best with good enough and discuss "for whom"

**Comment by samumantha** [comment]
Please read and adapt the sections on target audience and challenges with defining a target audience. I currently cannot come up with short nice sentences.
