### ISSUE TITLE
Unsorted thoughts on 2020.june

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/train-the-trainer#55]
My unsorted thoughts on 2020.june training (some of these will be split to other issues):

- [ ] we should have attending a CR as a prereq, if you want to teach CR
- [ ] progression: attend CR -> helper training -> (be a helper) -> instructor training
- [ ] do we teach tech stuff?  I don't think so, people need to learn that themselves by doing (possibly by being an instructor and figuringo ut it that way)
- [ ] do we teach people to be an instructor?  not everything, we lay groundwork but I think we can only really teach that by having them do it, and provide mentoring.  like we all should be doing to ourselves
- [ ] is SWC training a prerequisite?  of course it's good, I don't think there is so much need to duplicate: if they haven't, have them read the right book's sections
- [ ] if someone is SWC instructor-trained, I don't think we need to do much: have them go to a CR workshop, learn material some themselves, then do
- [ ] I could see benefit of networking and mechanics of joining, being hub, etc.
- [ ] I could see benefits of teaching incidental teachers how to make good lessons (as I've been saying a lot already)

- [x] I think today's sessions were good.
- [x] the example of teaching was a good development, I think.  for backwards design, I think that an example would have been good.  
- [ ] For teaching today, we could have recommended more complex things to teach.  presenting from slides doesn't give a good example of CR-style teaching.  we could recommend in first case, something that uses a shell (even if not CR lesson), and then if not that, some sort of demo.  Teaching demo with slides is last option
- [ ] direct contact with participants could have let us get more early feedback on what they wanted

**Comment by bast** [comment]
Closing. These are good thoughts but the material has moved on quite a bit since in the last 2-3 iterations and many of the good comments above are either in or not relevant anymore since we don't focus here on CR certification or CR teaching per se.
