### ISSUE TITLE
teaching online episode: backwards design

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/train-the-trainer#58]
Any comments on the plan below?  From what I can tell, I would make a new episode around this.

Summative assessments (goals of the episode):
- Understand the benefits and disadvantage of online teaching, compared to in-person
- Be able to take full advantage of online teaching tools (recording, streaming, etc - or does that go somewhere else?)
- Set up a good screen share
- Understand the benefits and disadvantages of team teaching
- Prepare for the teaching demo

Exercises:
- (if any ideas, give them here, but I might just directly make them up to the lesson, one discussion point or doing point for each of the above things).
- Show different screen-shareds (get screenshots from our previous videos).  Describe pros and cons of each.
- Fill in the table: {advantages of online, advantages of in-person} x {content, technical setup}

Reference material
- Screenshare: https://coderefinery.github.io/manuals/instructor-tech-setup/
- Presenting hints: https://coderefinery.github.io/manuals/presenting/
- Online training: https://coderefinery.github.io/manuals/online-training/  (or does this go elsewhere?)
- **question**: I'm not sure if this is the right place to go into the [instructor-intro](https://coderefinery.github.io/manuals/instructor-intro/) which is about instructor/helper/hackmd/expert-helpers, or does that go in another place?

**Comment by bast** [comment]
I think we have this now. Closing.
