### ISSUE TITLE
Session 4: Workshop streaming practices and post-workshop tasks

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#71]
**Preliminary learning objectives:**
- Get to know what happens "behind the stream" of a workshop
- Get to know ways of quick video editing to be able to provide accessible videos

**Initial schedule suggestion:**
- 1,5 hour streaming: setup, why we stream etc
- 1 hour recordings

**Instructor interests and materials documents**
- streaming: @rkdarst 
- video editing: @rkdarst 

Host for this session: @dhanyapushpadas 
Coordinator for this session: @rkdarst ?

**Comment by samumantha** [comment]
See also #82 and #83

**Comment by rkdarst** [comment]
Overall purpose:
- Make the whole streaming idea seem less complicated/scary?
- Show a preview of what the broadcaster sees

Plan of the day (each point becomes one episode):
- "why we stream" - general discussion, history of how we got here, etc. (15 min) - invite some guests to chat about it.
- "behind the stream" - general non-technical overview to make it less scary (30 min) - someone interviews Richard about how the stream works, and rkdarst shares the screen and shows it.  The purpose isn't to teach how it works but make it less scary (and prepare for the next days).
  - rkdarst provides ordered list of topics to ask about. 
- video editing process (ffmpeg-editlist) (20 min demo, 20 min hands-on).
  - Mostly a repeat of the "tromsø in person meeting" day 1 session.
- OBS introduction (20 min)
  - "how does streaming actually work?", broad intro and making it seem less scary and how everyone can do it.  But theory/demo and stuff.
  - https://coderefinery.github.io/manuals/obs/
- Setting up OBS for a streaming course (rest of time)
  - Go through how to use this repo: https://github.com/coderefinery/obs-config
  - Prepare someone to do it themselves.
- What's next? (10-15 min follow up).
  - In-person meeting to actually practice and get advice
  - Roleplay doing the livestream stuff (including the co-teaching side and all).
