### ISSUE TITLE
Session 3: About teaching & cool things we all would like to share

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#72]
Issue to discuss the full session 3. Please use new issues for single episode discussions and assignments to indicate that you are working on something.

**Preliminary learning objectives:**
- Get to know the teaching philosophies of CodeRefinery instructors
- Get to know the principle of co-teaching: How we do it and how you can too
- Share your own favorite tools or teaching gem
- ...?

**Schedule:**
- 15 min intro
- 30 min: computational thinking
- 30 min: teaching philosophies
- 30 min: co-teaching (moved here from Session 2)
- 35min: sharing teaching tips, tricks, tools etc by all
- 10 min outro

**Instructors **
- co-teaching.md:  @stepas-toliautas , @bast 
- teaching-philosophies.md: @blindij , @stepas-toliautas 
- computational-thinking.md: @linguist89 
- gems facilitator: @samumantha 

Host for this session: @samumantha 
Coordinator for this session: @samumantha

**Comment by samumantha** [comment]
Schedule request by @linguist89 : Computational thinking first thing in the morning.

**Comment by bast** [comment]
Please add timing overview to https://coderefinery.github.io/train-the-trainer/guide/.

**Comment by samumantha** [comment]
Suggestion added : https://github.com/coderefinery/train-the-trainer/pull/123

**Comment by bast** [comment]
I added 5 mins outro to https://coderefinery.github.io/train-the-trainer/guide/ but now it does not add up. I did not want to just shorten other episodes but some will need to be shortened.

**Comment by samumantha** [comment]
Thanks, will look into it!

**Comment by samumantha** [comment]
Hei @stepas-toliautas, what does it take to finalize the co-teaching episode? 
Would you take the lead on this episode? 
And would you like to co-teach the teaching philosophies episode?

**Comment by stepas-toliautas** [comment]
> Hei @stepas-toliautas, what does it take to finalize the co-teaching episode? Would you take the lead on this episode? And would you like to co-teach the teaching philosophies episode?

What it takes -- mostly time to sit down for it :) most likely by Friday, might be today/ tomorrow as well.
Also, it definitely needs an experienced CR member to co-teach about co-teaching -- any volunteers?
For teaching philosophies, I'm very much OK to be the co-pilot, yes.

**Comment by samumantha** [comment]
Sorry for the double posting. 
Thanks! 
I'll find you a co-teacher for the co-teaching episode :)

**Comment by samumantha** [comment]
@linguist89 @blindij @stepas-toliautas 
Is there anything that learners need to prepare/install/think about/ know to follow or understand your session on Day 3 that we should mention in the email going out tomorrow? Current email draft: https://github.com/coderefinery/train-the-trainer/issues/100#issuecomment-2302423742

**Comment by samumantha** [comment]
I'll have to send this email to participants now as is. However, if something still comes up that would be good that participants know about beforehand, please let me know asap and we can send an additional email.

**Comment by samumantha** [comment]
Thanks everyone for your work and presentations! 
Please add your own feedback (wrt to teaching, organization, materials etc): https://github.com/coderefinery/train-the-trainer/issues/149
