### ISSUE TITLE
Session 2: Tools and techniques adopted in CodeRefinery workshops

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#73]
Issue to discuss the full session 2. Please use new issues for single episode discussions and assignments to indicate that you are working on something.

**Preliminary learning objectives:**
- Understand the general structure of CodeRefinery workshops and why it is the way it is
- Get to know the different roles of a workshop and which ones are the most essential ones
- Understand the importance of  installation instructions and how they contribute to learners 
- Understand the importance of onboarding and a welcoming community for volunteers in a workshop
- Be able to provide a highly interactive online workshop environment with collaborative documents
- Be aware of the importance of a well planned screenshare and sound quality

**Initial schedule suggestion:**
- 45 min: workshop overview, roles, onboarding/installation, helpers
- 45 min: collaborative doc/interaction ( + usage during whole workshop)
- 45 min: screenshare & sound
- ~30 min for intro and free to distribute where needed (co-teaching episode moved to session 3)

**Instructor interests and materials documents**
- overview.md & onboarding.md (workshop overview, roles, onboarding/installation, helpers):  @dhanyapushpadas , @samumantha , @rkdarst , @stepas-toliautas 
- screenshare.md:  @blindij , @rkdarst , @bast , @HaoZeke 
- sound.md : @rkdarst , @dhanyapushpadas , @HaoZeke 
- collaborative_notes.md: @dianaiusan , @blindij , @bast , @HaoZeke  
- @linguist89 ?

Host for this session: @samumantha 
Coordinatior for this session: @bast

**Comment by samumantha** [comment]
Coordinator for this episode: @bast

**Comment by bast** [comment]
I will coordinate the Aug 20 session (this session). My first goal will be to assign a lead on each of the 4-5 episodes and the lead will draft the first version of each episode. I will also draft one of those.

To lower the notification noise, I will reach out to people individually and then summarize here. Based on the feedback from potential instructors and co-instructors I will create a more detailed schedule and help preparing the episode pages.

**Comment by bast** [comment]
Persons who will write first draft (thanks so much for your email replies!):
- overview.md: Samantha
- onboarding.md: Samantha
- co-teaching.md: Stepas
- screenshare.md: Radovan
- sound.md: Richard
- collaborative_notes.md: Bjørn

Please don't hesitate to ask for help if unclear where/how
and don't hesitate to indicate if you don't have time
to draft and would prefer if someone else did it.

**Comment by samumantha** [comment]
Onboarding and overview drafts started on `overview` branch; 
Happy to discuss content and especially also exercises discussions in #86 and #87 :)

**Comment by samumantha** [comment]
co-teaching moved to session 3; which leaves some more time for other stuff here, we need some time for intro in the morning, but if nothing else comes to mind we could do a fun session where we talk about **icebreakers** (in collaborative doc vs in person vs online) and have participants do or come up with some?

**Comment by bast** [comment]
I like the idea! Discussing ice-breakers and how to set the stage and get participants settled into the event.

**Comment by samumantha** [comment]
-> added an issue for this: #110

**Comment by bast** [comment]
Timing suggestion added to https://coderefinery.github.io/train-the-trainer/guide/#timing

**Comment by samumantha** [comment]
CodeRefinery project info could be "read before joining"? + Q&A section in notes about it?

**Comment by samumantha** [comment]
Working on overview and onboarding here: https://github.com/coderefinery/train-the-trainer/pull/130

**Comment by samumantha** [comment]
Questions to discuss in call on Friday: 
- Any prerequisites that we need to inform participants about beforehand? Any background knowledge that would make it easier to follow?
- Timings ok?

**Comment by bast** [comment]
Instructor line-up:
- Intro: SW
- Collaborative notes: BL+RB
- CR project and workshop from different perspectives: SW+RD
- Sound: RD+RB
- Screenshare: RB+BL
- Outro: SW

**Comment by bast** [comment]
Done :balloon:
