### ISSUE TITLE
Session 1: Contributing to and reusing CodeRefinery lesson materials

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#74]
Issue to discuss the full session 1. Please use new issues for single episode discussions and assignments to indicate that you are working on something.

**Preliminary learning objectives**
- Understand how collaborative development of lesson material works
- Be able to contribute to existing CodeRefinery lessons
- Undertstand how the lesson template is used to create new lessons
- Get to know the reasons and sources of inspiration behind major lesson and workshop updates

**Initial schedule suggestion:**
- 1 hour for lesson development
- 1 hour for lesson template
- 30 min for the survey

**Instructor interests**
- lesson_development.md :  @bast , @rantahar  , @johanhellsvik  , @dianaiusan
- lesson_template.md :  @bast , @dianaiusan , @rkdarst 
- post_workshop_survey.md : @code4yonglei @bast 

Host for this session: @samumantha 
Coordinator for this session: @samumantha ( @rantahar )

Related issues: #85 #84 and #88

**Comment by rantahar** [comment]
Draft for lesson development session added (PR #103)

**Comment by rantahar** [comment]
I want to say a bit more about exercises and assessments, but I still need to think a bit first.

**Comment by samumantha** [comment]
15 min intro
45 min lesson design , 15 min break , 45 min lesson template, 15 min break, 45 min survey and feedback

lesson design and survey: RB
lesson template: RD, SW prepares questions

**Comment by bast** [comment]
I will add timing info to instructor guide and then I will close the issue.
