### ISSUE TITLE
Episode: co-teaching

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#78]
Available old/other materials on the topic: 
- https://coderefinery.github.io/train-the-trainer/branch/community-teaching/team-teaching/
- https://coderefinery.github.io/train-the-trainer/branch/instructor-training/03-teaching-style/#
- https://coderefinery.github.io/manuals/co-instructors/

You do not need to reuse anything, but can :)

**Comment by stepas-toliautas** [comment]
I've drafted initial content at #97.
Comments on what topics to include/ leave out are welcome, I'd expand the material based on them.

**Comment by bast** [comment]
We would like to move the co-teaching episode to day 3.

Motivation:
- Re-balance a possibly too full day 2 with currently a bit empty day 3.
- Stepas would also prefer that.
- Samantha suggested this and agrees.

Is this OK for you @rkdarst @blindij @dianaiusan?

**Comment by samumantha** [comment]
Ups I jumped the gun a bit here, and moved it already in the issues. Sorry for that! 
Your opinion matters and we can still move it around to make it fit for everyone involved.

**Comment by blindij** [comment]
This is ok for me.

**Comment by samumantha** [comment]
Coordinator note: Draft in lesson materials :heavy_check_mark:

**Comment by samumantha** [comment]
Moi, what kind of help is needed to finalize this episodes material? 
Any ideas for co-teachers?

**Comment by stepas-toliautas** [comment]
> Moi, what kind of help is needed to finalize this episodes material? Any ideas for co-teachers?

Yes, I would appreciate subjective opinions of some long-runners (@samumantha, @bast, @blindij ...) on whether this episode should focus on contact-session [team teaching](https://coderefinery.github.io/manuals/team-teaching/), or can also review slightly wider context, including [here](https://coderefinery.github.io/manuals/co-instructors/), [here](https://coderefinery.github.io/manuals/instructor-intro/), 2a [here](https://coderefinery.github.io/manuals/online/), and open-course / material collaboration strategies. In first case, I'd spend more time about technique(s) and how to get one's teaching there, in second case I'd add audience poll/ discussion (Session 2 break-out rooms looked good for that) on the co-teaching experience they already had or seen and then summarize.
For co-teachers, anyone with CR perspective is welcome, as mine is still somewhat of an "outsider" :)

**Comment by bast** [comment]
I am actually not 100% sure I understand the two options :-) but I would:
- add a breakout-room discussion if possible
- focus on teaching together instead of alone and explore this in the context of how it changes onboarding/preparation and also the delivery
- we can also discuss challenges (more coordination, teaching styles need to match up, not every learner likes it)
- not necessarily online-only but also your experiences with it online or in-person

**Comment by rkdarst** [comment]
With ASC people who are teaching in the next CR workshop, we went over a teacher prep (tech stuff and co-teaching).  Tihs is a about co-teaching.

I tried to think of "how would I prepare someone to co-teach the first time?" and came up with the below.  Maybe it's helpful?  (If there was something I would add, it is some exercises where people have to practice one person leading and the other following).  I would probably continue to revise this as I see how it goes:

Below is the steps I came up with:

If you haven't taught before: first learn the lesson, go through demos, etc.

* Decide appropriate co-teaching model:  
  * [https://coderefinery.github.io/manuals/team-teaching/](https://coderefinery.github.io/manuals/team-teaching/)  
  * "guide" (going through material) and "typer" (doing demos, only typing what the other person says, asking questions, slowing things down)  
    * Better when there are more demos  
  * "interviewer" (asking questions from new person's point of view, setting pace, watching notes) and "interviewee" (going into technical details)  
    * Better when there are less demos  
  * Invite a third person to raise questions from the notes?  
* Decide 3 main messages of the session  
* To Do: practice the first \~5 minutes and last \~5 minutes first.  
  * Show this to someone else for feedback.  
* Plan the schedule  
  * Don't be too ambitious (it'll go slower than you think)  
  * Don't forget breaks and Q\&A times.  
* Decide who manages each of these (these can change during different sections):  
  * Moving from topic to topic  
  * Explaining details  
  * Typing  
  * Watching the Notes  
* Discuss how to avoid the "two captions" problem  
* Run-throughs  
  * The first \~5 and last \~5 minutes thing from above, but with roles determined  
  * \~Whole lesson with the "follower" person *not* doing any leading \[except during dedicated pauses, questions asked to them, and important questions they have\].  Discuss how it went  
  * Run through bits and pieces as needed  
* Revise schedule  
* Revise demos and exercises as needed.  
* just go\!

**Comment by samumantha** [comment]
Thanks everyone, this looks great! Looking forward to the episode.
