### ISSUE TITLE
Episode: postworkshop survey

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#88]
Old/Other materials on the topic:
- WIP: https://github.com/coderefinery/2024-post-workshop-survey
-

**Comment by bast** [comment]
How long is this session? And what should be the learning outcomes? Me presenting and discussing the results? What should learners take from this?

**Comment by samumantha** [comment]
Currently in plan for 30 min, but can be adjusted.

To me it seems that this kind of 'longer term surveys' are not done much but people would like to. While the results are certainly interesting,  I thought that in this context the design and idea why we do it, how the questions are asked and what we do with the results might be more interesting 🤔

Maybe even an exercise looking at different ways how a question in such survey can be asked and discussing? 

Ie some from the original survey and then the questions after fixes through RiSE survey people? To discuss about leading questions etc.

**Comment by bast** [comment]
OK - then I will have to do some archaeology in previous iterations. But I see now better the point.

**Comment by bast** [comment]
- blog post: https://coderefinery.org/blog/2024/08/10/post-workshop-survey/
- repo: https://github.com/coderefinery/2024-post-workshop-survey
- Zenodo/DOI: https://doi.org/10.5281/zenodo.13292363

I am summarizing this here now. @code4yonglei for info.
