### ISSUE TITLE
Add yourself as instructor!

### ISSUE THREAD

**Issue by samumantha** [coderefinery/train-the-trainer#98]
Please add yourself to the [index.md](https://github.com/coderefinery/train-the-trainer/blob/main/content/index.md) page in content folder under "instructors and facilitators", alphabetical order for last name.

**Comment by bast** [comment]
I added few people who are preparing days 1 and 2. Later we can add more.

**Comment by samumantha** [comment]
Can still be done if we get more than currently mentioned.
Still closing this for now as done
